#!/bin/bash
# Save this file to .promptrc in home directory to enable prompt style and color
# Author: Suphannee Sivakorn (https://github.com/ssivakorn)
# Color can be picked from http://geoff.greer.fm/lscolors/

# Prepare personalize prompt status style and color
function set_promptcmd {

    RESET="\[\033[00m\]"

    # Define my personal colors

    RED="\[\033[38;5;1;48;5;${DEFAULT_BG}\]"

    GREEN="2"
    BLUE="27"
    WHITE="255"
    BLACK="232"
    GREY="245"
    ORANGE="208"
    PINK="205"
    YELLOW="3"
    PURPLE="141"

    FGCOLOR="$GREEN_FG"
    BGCOLOR="$GREEN_FG"

    case "$1" in
        green)
            FGCOLOR=$GREEN
            BGCOLOR=$GREEN
            ;;

        blue)
            FGCOLOR=$BLUE
            BGCOLOR=$BLUE
            ;;

        orange)
            FGCOLOR=$ORANGE
            BGCOLOR=$ORANGE
            ;;
        pink)
            FGCOLOR=$PINK
            BGCOLOR=$PINK
            ;;
        purple)
            FGCOLOR=$PURPLE
            BGCOLOR=$PURPLE
            ;;
        yellow)
            FGCOLOR=$YELLOW
            BGCOLOR=$YELLOW
            ;;
        *)
            FGCOLOR=$BLUE
            BGCOLOR=$BLUE
            ;;
    esac

    FGCOLOR="\[\033[38;5;${FGCOLOR}m\]"
    BGCOLOR="\[\033[48;5;${BGCOLOR}m\]"

    FGWHITE="\[\033[38;5;${WHITE}m\]"
    BGWHITE="\[\033[48;5;${WHITE}m\]"

    FGBLACK="\[\033[38;5;${BLACK}m\]"
    BGBLACK="\[\033[48;5;${BLACK}m\]"

    FGGREY="\[\033[38;5;${GREY}m\]"
    BGGREY="\[\033[48;5;${GREY}m\]"

    ###########################

    let fillsize=${COLUMNS}
    fill=""
    while [ "$fillsize" -gt "0" ]
    do
        fill="${fill}—" # fill
        let fillsize=${fillsize}-1
    done

    fill="${fill}"
    #liner_line="${RESET}${FGCOLOR}${fill}${RESET}\n"
    liner_line=""
    status_line="${FGGREY}\@ • "
    prompt_line="${RESET}${BGCOLOR}${FGBLACK}\u@\h \$ ${RESET}${FGCOLOR} ${RESET}"

    if [ -n "$VIRTUAL_ENV" ]
    then
        py_virtualenv=`basename $VIRTUAL_ENV`
        status_line="${RESET}${LIGHTGREY}\@ • (${py_virtualenv}) "
    fi
    status_line="${status_line}\w ${RESET}"
    command_style="${RESET}" # \[\033[1;29m\]" # bold black

    export PS1="${liner_line}${status_line}\n${prompt_line}${command_style}"
}
