#!/bin/bash

# Prompt setup
mkdir -p $HOME/.config
mkdir -p $HOME/.config/fish
mkdir -p $HOME/.config/fish/functions

path=`pwd`
ln -f -s $path/fish_prompt.fish $HOME/.config/fish/functions/fish_prompt.fish
ln -f -s $path/fish_right_prompt.fish $HOME/.config/fish/functions/fish_right_prompt.fish

# Color
fish basic_config.fish
fish color_config.fish
