#!/bin/bash
set -e

echo "Setting up tmux configurations"

# Remove current tmux configurations
rm -rf $HOME/.tmux.conf
rm -rf $HOME/.tmux_helpers.sh

# TMUX plugins (https://github.com/tmux-plugins)
rm -rf $HOME/.tmux/plugins/tpm
git clone -q https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm


# TMUX configuration
path=$(pwd)
ln -s -f "$path/tmux.conf" "$HOME/.tmux.conf"

# Install helper functions for status bar
ln -s -f "$path/tmux_helpers.sh" "$HOME/.tmux_helpers.sh"

echo ""
echo "Please activate all tmux-plugins: https://github.com/tmux-plugins"
echo "tmux and prefix + I"
