#!/bin/bash
set -e

echo "Setting up tmux configurations"

# Remove current tmux configurations
rm -rf ~/.tmux.conf

# TMUX plugins (https://github.com/tmux-plugins)
rm -rf ~/.tmux/plugins/tpm
git clone -q https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Install helper functions for status bar
cp -f "$(pwd)/tmux_helpers.sh" "$HOME/.tmux_helpers.sh"

# TMUX configuration
path=$(pwd)
ln -s -f "$path/tmux.conf" "$HOME/.tmux.conf"

echo ""
echo "Please activate all tmux-plugins: https://github.com/tmux-plugins"
echo "tmux and prefix + I"
