# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="tonotdo" # set by `omz`

ZSH_THEME=""

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-prompt fzf zsh-autosuggestions zsh-syntax-highlighting)


source $ZSH/oh-my-zsh.sh

# User configuration
ZSH_HIGHLIGHT_STYLES[command]='fg=33'                   # bright blue
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=118'            # lime green
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=196,bold'       # red
ZSH_HIGHLIGHT_STYLES[path]='underline'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=215'   # orange-ish yellow
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=215'   # orange-ish yellow
ZSH_HIGHLIGHT_STYLES[assign]='fg=135'                   # purple
ZSH_HIGHLIGHT_STYLES[comment]='fg=240'                  # grey
ZSH_HIGHLIGHT_STYLES[globbing]='fg=43,bold'

export TERM=xterm-256color
export COLORTERM=truecolor

# Define common colors
color_normal='%f'
color_grey='%F{240}'
color_red='%F{1}'                   # red
color_green='%F{118}'               # lime green #96c93c
color_blue='%F{33}'                 # bright blue #087fff
color_yellow='%F{215}'              # orange-ish yellow

# Define prompt colors
color_error=$color_red
color_user=$color_blue
color_host='%F{42}'                 # sea green/teal #1eb980
color_sep='%F{135}'                 # purple #ff3399
color_prompt='%F{199}'              # hot pink #ff3399
color_time=$color_grey
color_virtualenv='%F{218}'          # dark orange #ff8c00
color_branch_dirty=$color_yellow
color_branch_clean=$color_green
color_path=$color_normal

prompt_char='$ '
prompt_userhost_sep='@'


export VIRTUAL_ENV_DISABLE_PROMPT=1
function virtualenv_prompt {
  if [[ -n "$VIRTUAL_ENV" ]]; then
    local venv_name="${VIRTUAL_ENV##*/}"
    echo "${color_grey}(${color_virtualenv}${venv_name}${color_grey})${color_normal} "
  fi
}


ZSH_THEME_GIT_PROMPT_PREFIX="${color_grey}[${color_normal}"
ZSH_THEME_GIT_PROMPT_SUFFIX="${color_grey}]${color_normal}"
ZSH_THEME_GIT_PROMPT_SEPARATOR=" "
ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[green]%}%{●%G%}"
ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg[yellow]%}"

PROMPT='${color_user}%n${color_sep}${prompt_userhost_sep}${color_host}%m${color_normal} %~ $(git_super_status)
$(virtualenv_prompt)${color_prompt}${prompt_char}${color_normal}'


ZLE_RPROMPT_INDENT=1
RPROMPT='${color_time}%D{%H:%M:%S}${color_normal}'

export CLICOLOR=1
export LSCOLORS=ex
export LS_COLORS="di=34:ex=31"
alias ll="ls -alG"

zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"


# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
