#!/bin/bash

# Prompt setup
mkdir -p $HOME/.config
mkdir -p $HOME/.config/fish
mkdir -p $HOME/.config/fish/functions

# Install omf
# Remove previous installation
rm -rf $HOME/.local/share/omf

# https://github.com/oh-my-fish/oh-my-fish
curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish


path=`pwd`
ln -f -s $path/omf/init.fish $HOME/.config/omf/init.fish
# ln -f -s $path/fish_prompt.fish $HOME/.config/fish/functions/fish_prompt.fish
ln -f -s $path/fish_right_prompt.fish $HOME/.config/fish/functions/fish_right_prompt.fish

exec $(which fish) -l

omf install kawasaki

# Color
fish basic_config.fish
fish color_config.fish
