#!/bin/bash

path=$(pwd)

# Directories
mkdir -p $HOME/.config/fish/functions

# Install omf (removes previous installation)
rm -rf $HOME/.local/share/omf
curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish

# Symlinks
ln -f -s $path/omf/init.fish $HOME/.config/omf/init.fish
ln -f -s $path/fish_right_prompt.fish $HOME/.config/fish/functions/fish_right_prompt.fish

# Install kawasaki theme
fish -c "omf install kawasaki"

# Apply color and basic config
fish $path/color_config.fish
fish $path/basic_config.fish
